### ISSUE TITLE
Week 2: Review My App

### ISSUE THREAD

**Issue by bluyam** [bluyam/flicks#3]
Hi there! My app is ready for review. Please excuse the slowness of the walkthrough. :3 /cc @codepathreview

**Comment by codepathreview** [comment]
**Awesome**!!! This is the best and the most creative submission I've ever seen! :tada: :star2: :boom:  You did more than expected.... The UI is very impressive :heart_eyes: 

The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

### Some small comments:
- Good job using `UITextView` to display movie's overview.
- It will be better if you disable `Save` button with saved movies. For now, I can save a movie many times.
  <img width="315" alt="screen shot 2016-02-01 at 11 18 38 pm" src="https://cloud.githubusercontent.com/assets/7917093/12723038/40b1a88e-c93a-11e5-8ee7-d907e6f34896.png">
- Please only use `self` in case of necessary. For example, you can remove all `self` keywords in this code:

``` Swift
func similarDataInnerOperation(dictData: NSDictionary) {
    self.similarMovies = (dictData["results"] as? [NSDictionary])!
    self.similarCollectionView.reloadData()
    if self.similarMovies!.count == 0 {
        self.scrollView.contentSize = CGSize(width: self.scrollView.frame.size.width, height: 1060)
        self.similarCollectionView.alpha = 0
        self.similarMessageLabel.alpha = 1
    }
}
```
- You declared `apiKey` many times in your project. You can declare this variable after `import` code (out side the MoviesViewController class) to avoid this duplicating. So you can access this variable anywhere, even in other files.

Excellent submission overall :horse_racing: :100: 

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by bluyam** [comment]
Awesome feedback! :fireworks: 
By the way, I apologize for the misunderstanding: I spent **21 hours** on this portion of the assignment. I originally updated the time spent for the first part of the README but not the second - if that could be updated in the dashboard, I'd really appreciate it! :smiley:

**Comment by codepathreview** [comment]
Okay. I'll update your time spent in the dashboard. I wondered why you can complete all additional features with 1 hour :smile:
